FROM node:13.12.0-alpine

WORKDIR /app

COPY ./package.json package.json
COPY ./src src
COPY ./public public

RUN chown -R node:node /app && \
    npm install

EXPOSE 3000

USER node

CMD ["npm", "start"]

# layer size: 233 MB
# image size: 347 MB
